name: Create Release Draft

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tagname
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      
      - name: Create Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.tagname.outputs.tag }}
          name: Release ${{ steps.tagname.outputs.tag }}
          version: ${{ steps.tagname.outputs.tag }}
          publish: false  # Draft the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
