name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get semantic version
        id: semver
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
      
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ github.event.inputs.version }}  # Use the correct input value here
          name: Release ${{ steps.semver.outputs.version }}  # Use the correct step output here
          version: ${{ steps.semver.outputs.version }}  # Use the correct step output here
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN secret here
